# This file was generated by GoReleaser. DO NOT EDIT.
class MagnetisCrawler < Formula
  desc "Magnetis Crawler"
  homepage ""
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/alfredosegundo/magnetis-crawler/releases/download/v1.0.1/Magnetis Crawler_1.0.1_darwin_amd64.tar.gz"
    sha256 "9a43a1ff0f095df869f0cfbb8cb90fd9a8e2b189118a7eb72f711e16bf6ed5a7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/alfredosegundo/magnetis-crawler/releases/download/v1.0.1/Magnetis Crawler_1.0.1_linux_amd64.tar.gz"
      sha256 "6a546adbe781df57804e35ad4872710dd1787561e40f6d1043aca2514a8a4505"
    end
  end

  def install
    bin.install "magnetis_crawler"
  end

  test do
    system "#{bin}/magnetis_crawler -v"
  end
end
