# This file was generated by GoReleaser. DO NOT EDIT.
class MagnetisCrawler < Formula
  desc "Crawler of the json api of magnetis.com.br website"
  homepage ""
  version "1.0.4"
  bottle :unneeded

  if OS.mac?
    url "http://github.mycompany.com/alfredosegundo/magnetis_crawler/releases/download/v1.0.4/magnetis-crawler_1.0.4_Darwin_x86_64.tar.gz"
    sha256 "99f9d3d2754acf5e9b513cda6c5477c69e0dbf319e8663f56f784e687432772f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.mycompany.com/alfredosegundo/magnetis_crawler/releases/download/v1.0.4/magnetis-crawler_1.0.4_Linux_x86_64.tar.gz"
      sha256 "75a28a16756f6bbc54ab89f52c75731d5c995cc74ce58672ff19ee32df4b70b9"
    end
  end

  def install
    bin.install "program"
  end

  test do
    system "#{bin}/magnetis_crawler --version"
  end
end
