# This file was generated by GoReleaser. DO NOT EDIT.
class MagnetisCrawler < Formula
  desc "Crawler of the json api of magnetis.com.br website"
  homepage ""
  version "1.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/alfredosegundo/magnetis-crawler/releases/download/v1.0.6/magnetis-crawler_1.0.6_Darwin_x86_64.tar.gz"
    sha256 "b07c6af6d9ea20deb9016b997b6803451d4ee68d699c30f69969f83cc5ed58bc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/alfredosegundo/magnetis-crawler/releases/download/v1.0.6/magnetis-crawler_1.0.6_Linux_x86_64.tar.gz"
      sha256 "28cb297c5e4ab58662b1d05a99bfecac49bc07c1511ad691f24091fe7cfe6d14"
    end
  end

  def install
    bin.install "program"
  end

  test do
    system "#{bin}/magnetis-crawler --version"
  end
end
