# This file was generated by GoReleaser. DO NOT EDIT.
class MagnetisCrawler < Formula
  desc "Crawler of the json api of magnetis.com.br website"
  homepage ""
  version "1.0.5"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/alfredosegundo/magnetis_crawler/releases/download/v1.0.5/magnetis-crawler_1.0.5_Darwin_x86_64.tar.gz"
    sha256 "616768c8b36e1390134777481c009ecea3ac8d54ba192bb15d219aa491374005"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/alfredosegundo/magnetis_crawler/releases/download/v1.0.5/magnetis-crawler_1.0.5_Linux_x86_64.tar.gz"
      sha256 "110190f65c6dab330da5fa7cbb1f5a2fc74a1e35dba8fba52c27ef940d612425"
    end
  end

  def install
    bin.install "program"
  end

  test do
    system "#{bin}/magnetis_crawler --version"
  end
end
